### ISSUE TITLE
Can't install 0template on OSX

### ISSUE THREAD

**Issue by morevnaproject** [0install/0template#17]
It looks like this is because of missing python package:

```
$ 0install run http://0install.net/tools/0template.xml run
Can't find all required implementations:                                        
- http://0install.net/2007/interfaces/ZeroInstall.xml -> 2.3.10 (sha1new=31091e7ac1dde3fbfaeecae391db0ba7dbadd507)
    http://0install.net/tools/0template.xml 0.6 requires version 2.2-post..
- http://0install.net/tools/0template.xml -> 0.6 (sha1new=03a80899236770b139c3c4be1d2255e4644a1a32)
- https://apps.0install.net/python/python.xml -> (problem)
    http://0install.net/2007/interfaces/ZeroInstall.xml 2.3.10 requires version 3.4..
    http://0install.net/tools/0template.xml 0.6 requires version 2.7..
    No usable implementations:
      sha1new=1f411e645412b2e5bf9e28bdfa6a3b08b73a574c (2.7.2): We want a binary and this is source
      sha1new=0769fb909e4df8f33637c278a87c61a979e52dc7 (2.7.1): Not compatible with the requested OS type
      sha1new=c38fe8f18382ff8c8df0761db9c14f57b14f50c7 (2.7.1): Not compatible with the requested OS type
      sha1new=08d9b34d377b0713eeaf1e094b559d427c234c01 (2.7.1): We want a binary and this is source
      sha1new=846cb9f3a661e2b0f8416ccbed8cbb4bcf53b11a (2.7): We want a binary and this is source
      ...
- https://apps.0install.net/utils/gnupg.xml -> 1.4.18 (sha1new=6763fb31a919b51991db9ab109cbd05ee191057d)
    http://0install.net/2007/interfaces/ZeroInstall.xml 2.3.10 requires 'run' command

```

**Comment by morevnaproject** [comment]
Forgot to mention, that I tested this on OSX 10.9.

**Comment by morevnaproject** [comment]
Same error on OSX 10.10.

**Comment by talex5** [comment]
Do you have Python 3 installed?

**Comment by morevnaproject** [comment]
Yes. Here is a screenshot from 10.10:
![screenshot_005](https://user-images.githubusercontent.com/332868/77422354-e5efaf80-6dff-11ea-86fb-2f217c4e3ce6.png)

**Comment by talex5** [comment]
I don't have a mac to test on, but the CI runs a test that finds Python 3 on macOS:

  https://travis-ci.org/github/0install/0install/jobs/656279540#L3042

```
  - URI: https://apps.0install.net/python/python.xml
    Version: 3.7.6.0
    Path: (package:host:python:3.7.6.0)
```

What version of 0install are you using? There was a change about finding Python in 2.15.1 (the URI changed), which might affect it, so try with at least that version.

**Comment by morevnaproject** [comment]
Hi! Apologies for delay. I have 0install version 2.8 (downloaded from official website).
![screenshot_001](https://user-images.githubusercontent.com/332868/77882767-d94dda00-728b-11ea-9556-ca1cee78b676.png)

Could that be a problem with Brew's installation of Python?
![screenshot_003](https://user-images.githubusercontent.com/332868/77882802-eff43100-728b-11ea-86ed-0eef1097a921.png)

P.S. It is good to know that it works in CI. That means we can proceed with https://github.com/0install/apps/issues/40#issuecomment-602894905 ^__^ @bastianeicher

**Comment by bastianeicher** [comment]
@talex5 The latest pre-built 0install binaries available for Mac are still 2.8. Could you modify the Travis CI job to publish the built Mac binaries somewhere? I could then use those for a Mac job in [0install/apps/.github/workflows/update.yml](https://github.com/0install/apps/blob/master/.github/workflows/update.yml).

**Comment by morevnaproject** [comment]
How can I update my fersion of 0install on OSX?

**Comment by talex5** [comment]
I've added a GitHub action to build a zip of the build on macOS:
https://github.com/0install/0install/actions/runs/71248591

I don't have a mac to test it on though.

**Comment by bastianeicher** [comment]
See 0install/0install#74

**Comment by bastianeicher** [comment]
Should be enough to track this in 0install/0install#74.
